global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'rodweb-monitor'

storage:
  tsdb:
          #retention.time: 15d

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  #- job_name: 'node-prometheus'
  #  scrape_interval: 15s
  #  static_configs:
  #    - targets: ['node-exporter:9100']


  - job_name: 'node-test'
    scrape_interval: 15s
    static_configs:
      - targets: ["172.31.6.1:19000","172.31.6.2:19000"]

